### ISSUE TITLE
Indexing error when running test for Durable Function

### ISSUE THREAD

**Issue by tuanle07** [riezebosch/AzureFunctions.TestHelpers#10]
When I'm trying to run the integration test for Duration Function, the following error was thrown and I have no idea what caused that error:
`Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'FuntionName'`
Do I need to start the Storage Emulator locally first before running the test? @riezebosch 
PS: I'm using Azure Function v3 (.netcore 3.1) with Duration Function v2
Below is the entire log for your reference:
`---- System.InvalidOperationException : Functions must return Task or void, have a binding attribute for the return value, or be triggered by a binding that natively supports return values.
   at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 83
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 86
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 74
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 61
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(JobHost host, CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 105
   at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource 1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 358
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 101
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at PteMarkingFunction.Tests.IntegrationTests.DurableFunction() in C:\Users\Tuan Anh Le\source\repos\PTE Online Test\MarkingFunction.Tests\IntegrationTests.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 298
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 137`

**Comment by riezebosch** [comment]
You need to run the storage emulator first en set the storage connection string as described [here](https://github.com/riezebosch/AzureFunctions.TestHelpers#azure-storage-account).

But that's not what the exception is telling you, it doesn't understand the return value of your method. I've not seen that one before and I'm curious what the return type is.

**Comment by tuanle07** [comment]
@riezebosch : I figured out the issue comes from the fact that my durable function is HttpTriggered. If I do `builder.AddHttp()` it will give me an error related to `AuthenticationManager` cannot be loaded from `HttpAbstraction v3.1`. I think in your solution, you're using the `Microsoft.AspNetCore.Http v2.2`. Do you know how to solve this issue?

**Comment by tuanle07** [comment]
@riezebosch I found where the issue came from:
`[Obsolete] public override AuthenticationManager Authentication { get; } = null;`
`AuthenticationManager` was removed from .NetCore v3.1

**Comment by riezebosch** [comment]
You don't have to use the `DummyHttpRequest` like I'm showing here: https://www.youtube.com/watch?v=o1EqbeVF1EA&t=1505. The documentation currently suggests you should be using the `HttpRequest` anyways.

**Comment by tuanle07** [comment]
@riezebosch : I haven't used the `DummyHttpRequest` yet, but still I can't start the host coz it keeps throwing error related to the missing `AuthenticationManager` from .Net3.1 SDK.

**Comment by riezebosch** [comment]
Okay, I should probably drop that from the package then. Strange thing is though that it works for me when I also upgrade my test project to `netcoreapp3.1`.

**Comment by tuanle07** [comment]
@riezebosch : Most likely bcoz you're still having the .NET 2.2 SDK downloaded locally... `HttpContext` in v3 has removed that `AuthenticationManager` completely so I don't think you can override it in your `DummyHttpContext` in v3 thou. When would you be able to push a minor update to solve this issue? :)

**Comment by riezebosch** [comment]
I don't get which version you are using since the latest released version on nuget still has that property on it: https://www.nuget.org/packages/Microsoft.AspNetCore.Http

https://github.com/dotnet/aspnetcore/blob/522705f9a27b99ca4ad261f2e89fe51a77b2338e/src/Http/Http.Abstractions/src/HttpContext.cs#L48-L49

Are you able to share your project or at least create a repro? I'm more than happy to remove these parts of the package but I want to make sure what I'm actually fixing.

**Comment by tuanle07** [comment]
@riezebosch : This is the error I've got: 
`System.TypeLoadException : Could not load type 'Microsoft.AspNetCore.Http.Authentication.AuthenticationManager' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchReturnParameter()
   at System.Reflection.RuntimeMethodInfo.get_ReturnParameter()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IsJobMethod(MethodInfo method) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 110
   at System.Linq.Enumerable.WhereArrayIterator 1.MoveNext()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 69
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 74
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 61
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(JobHost host, CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 105
   at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource 1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 358
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 101
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---`

**Comment by riezebosch** [comment]
Indeed I found it in the docs: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#authentication-httpcontextauthentication-property-removed

But where do you get that version from? Is it a different package on nuget or do you get it from somewhere else?

**Comment by tuanle07** [comment]
@riezebosch : it comes from the official SDK. I didn’t have to download any packages on Nuget. Starting from .NET 3.0, I think all the packages are bundled into the SDK itself.

**Comment by riezebosch** [comment]
You're right. Apparently there's a new `<Project Sdk="Microsoft.NET.Sdk.Web">` which has implicit dependencies that are not from nuget. This makes targetting multiple platforms really hard I guess.

**Comment by tuanle07** [comment]
@riezebosch : that’s why migrating from .Net core 2.2 to 3.0, it will likely break things! So what’s your plan to fix this issue with your library?

**Comment by riezebosch** [comment]
Upgrade to `v3.2.80` 🎉  Thanks for submitting the issue and having this conversation.

**Comment by ekaradev** [comment]
Hi @riezebosch ,
I am using version 4.0.101 and I am getting the same error.

version : .net6

**Comment by riezebosch** [comment]
in-process or isolated worker process?

**Comment by ekaradev** [comment]
> in-process or isolated worker process?

@riezebosch 
in-process  


```csharp

 Environment.SetEnvironmentVariable("AzureWebJobsStorage", "UseDevelopmentStorage=true");
            using var host = new HostBuilder()
                .ConfigureWebJobs(builder => builder
                    .AddDurableTask(options =>  options.HubName = nameof(InboundDurableAmdpProductsOrchestratorFunction))
                    .UseWebJobsStartup(typeof(Startup), new WebJobsBuilderContext(), NullLoggerFactory.Instance))
                .Build();
            await host.StartAsync();
            var jobs = host.Services.GetService<IJobHost>();
            await jobs.
                Terminate()
                .Purge();

```

**Comment by riezebosch** [comment]
and what's the error?

**Comment by ekaradev** [comment]
> and what's the error?

Error:
![image](https://github.com/riezebosch/AzureFunctions.TestHelpers/assets/17519791/3655cd2f-8811-42f2-a324-e72281a5fc10)

**Comment by riezebosch** [comment]
I'm facing the exact same error when testing out isolated functions 😢 . Strange fact for you is that all other tests already target `net6.0`
